apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress
data:
  5432: "bitnami/postgresql:16.1.0-debian-11-r4:5432"
  # postgresql-endpoint: "postgresql.postgresql.svc.cluster.local:5432"
